[[services]]
name = "salt-master"
command = "/usr/bin/salt-master"
args = ["-l", "info"]
# args = ["-d"]
# log_file = "/var/log/salt/master"

[[services]]
name = "salt-api"
command = "/usr/bin/salt-api"
args = ["-l", "info"]
