[timeouts]
# Time to wait after a service starts before running its `pos_script` (seconds)
post_script_timeout = 7
# Max time for a service to shut down gracefully before being killed (seconds)
service_shutdown_timeout = 10
# Max time for the entire shutdown sequence to complete (seconds)
global_shutdown_timeout = 30
# Max time to wait for a dependency to start (seconds)
dependency_wait_timeout = 300

[[services]]
name = "nginx"
command = "/usr/sbin/nginx"
pre_script = "/scripts/pma-auth.sh"
args = ["-g", "'daemon off;'"]
# Optional: run as specific user
# user = "www-data"
# Optional: redirect logs to a file instead of PTY
# log_file = "/var/log/nginx/access.log"
# Start only if true (defaults to true when omitted)
enabled = true
# If true, failure triggers global shutdown
required = true
# Service dependency coordination
depends_on = "php-fpm"
wait_after = 3

[[services]]
name = "node-app"
command = "/usr/bin/npm"
args = ["--prefix", "/srv/nodejs", "run", "dev"]
# user = "node"
# log_file = "/var/log/node-app.log"
enabled = true
required = false
# depends_on = ""
# wait_after = 0
# pre_script = "/scripts/node-pre.sh"
# pos_script = "/scripts/node-pos.sh"

[[services]]
name = "php-fpm"
command = "/usr/local/sbin/php-fpm"
pre_script = "/scripts/php-fpm.sh"
# user = "www-data"
# log_file = "/var/log/php-fpm.log"
enabled = true
required = true
# depends_on = ""
# wait_after = 0
# pos_script = "/scripts/php-fpm-pos.sh"

[[services]]
name = "mariadb"
command = "/usr/bin/mysqld"
pre_script = "/scripts/mariadb.sh"
pos_script = "/scripts/is_empty.py"
args = [
  "--user=mysql",
  "--console",
  "--skip-name-resolve",
  "--skip-networking=0"
]
# user = "mysql"
# log_file = "/var/log/mysql/mysqld.log"
enabled = true
required = false
# depends_on = ""
# wait_after = 0

[[services]]
name    = "fastapi"
command = "uvicorn"
args = [
  "main:app",
  "--app-dir=/srv/python",
  "--host=0.0.0.0",
  "--port=8012",
  "--reload",
  "--log-level=debug"
]
# user = "www-data"
# log_file = "/var/log/fastapi.log"
enabled = true
required = false
# depends_on = "mariadb"
# wait_after = 2
# pre_script = "/scripts/fastapi-pre.sh"
# pos_script = "/scripts/fastapi-pos.sh"
