# Simulate a database that takes time to start up
[[services]]
name = "database"
command = "sh"
args = ["-c", "echo 'Booting database...'; sleep 5; echo 'Database is ready!'"]
enabled = true
required = true

# A web application that depends on the database
[[services]]
name = "web-app"
command = "sh"
args = ["-c", "echo 'Web app connecting to database...'; echo 'Web app started successfully!'"]
enabled = true
required = true
depends_on = "database" # This service will wait for 'database' to start
wait_after = 2          # Wait 2 extra seconds after 'database' starts
